/* eslint-disable react/jsx-no-undef */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Adjust the usage of Header based on your needs */}
        <Header Top /> 
        {/* or */}
        {/* <Header><Top /></Header> */}
        {children}
      </body>
    </html>
  );
}

